set nocompatible                        " don't worry about vi compatibility

filetype on                             " file type detection
filetype plugin on                      " plugins for specific file types
filetype indent on                      " indentation for specific file types

syntax on                               " syntax highlighting

set autoindent                          " copy indent from current line
set expandtab                           " num spaces to insert for tab
set shiftwidth=2                        " num spaces for autoindent
set list                                " display unprintables
set listchars=tab:._                    " how to display tabs

set ruler                               " show cursor line and column pos
set number                              " show line numbers
set numberwidth=3                       " line number gutter width
set colorcolumn=80,120                  " highlighthed columns
set nowrap                              " don't wrap lines
" toggle crosshair
nnoremap <leader>c :set cursorline! cursorcolumn! <cr>

" remembering twixt sessions
"  'N   :  marks will be remembered for up to N previously edited files 
"  "N   :  will save up to N lines for each register
"  :N   :  up to N lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction
augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
